language: cpp
dist: xenial
compiler: gcc
os: linux
script:
- g++ -std=c++11 -Wall -Wno-sign-compare -Wno-reorder -Wno-unused-function example/Examples.cpp -o ExcelFormat_example
- ./ExcelFormat_example