language: cpp
dist: bionic
compiler: gcc
os: linux

env:
  global:
  - MAKEFLAGS="-j 2"

before_install:
- pip install --user cpp-coveralls

script:
- cmake CMakeLists.txt
- make
- ./ExcelFormat_Example

after_success:
- coveralls --exclude vs_solution --exclude CMakeFiles --gcov-options '\-lp'
